"""Read-only classification and exact transitions for plugin-era projects."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import shlex

from provider.claude_hooks import render_dispatcher_hooks as claude_hooks
from provider.codex_hooks import render_dispatcher_hooks as codex_hooks

from .reconcile import Contribution, ExactDeleteIntent, ExactFileIntent


_LEGACY_LAUNCHER = '''#!/bin/bash
# playbook-managed — do not edit; regenerated by playbook plugin
SCRIPT="$(find ~/.claude/plugins -path "*/playbook/scripts/{command}" -type f 2>/dev/null | head -1)"
if [ -z "$SCRIPT" ]; then
    echo "Error: playbook plugin not found." >&2
    echo "Install: claude plugin marketplace add horiacristescu/claude-playbook-plugin" >&2
    exit 1
fi
exec "$SCRIPT" "$@"
'''
_SHIM = '''#!/bin/sh
# playbook-harness compatibility shim v1
exec {command} "$@"
'''
_LAUNCHERS = {
    ".claude/bin/tasks": ("tasks", "pb-tasks"),
    ".claude/bin/sandbox": ("sandbox", "pb-sandbox"),
}
_LEGACY_MONITOR_LAUNCHER = _LEGACY_LAUNCHER.format(command="monitor")
_LEGACY_MONITOR_COMMAND = 'bash "$CLAUDE_PROJECT_DIR/.claude/hooks/monitor-nudge.sh"'
_LEGACY_MONITOR_HOOK_DIGESTS = frozenset(
    {
        "19d3a478f6da2660295041191b4a20683f94ebad6eb79478204d7b98dee07071",
        "ceca973b5b113fbe4d847f58f23aa972cdc728d997e29ab3033759ecd61782d5",
    }
)
_CLAUDE_SCRIPTS = {
    "SessionStart": "session-start-hook",
    "PreToolUse": "task-gate-hook",
    "UserPromptSubmit": "chat-log-hook",
    "PostToolUse": "state-echo-hook",
    "Stop": "stop-hook",
    "SessionEnd": "session-end-hook",
}
_CODEX_SCRIPTS = {
    "UserPromptSubmit": "codex-user-prompt-hook",
    "Stop": "codex-stop-hook",
    "PreToolUse": "codex-apply-patch-hook",
    "PostToolUse": "codex-apply-patch-hook",
}
_MARKETPLACE = "claude-playbook-marketplace"
_PLUGIN_KEY = "playbook@claude-playbook-marketplace"
_ACTIVE_CONSUMER_DIRS = {
    ".claude",
    ".codex",
    ".omp",
    ".github",
    "bin",
    "scripts",
    "tools",
    "ops",
}
_ACTIVE_CONSUMER_FILES = {
    "AGENTS.md",
    "CLAUDE.md",
    "GEMINI.md",
    "Makefile",
    "package.json",
    "pyproject.toml",
}
_LEGACY_RUNTIME_NAMES = {
    "tasks",
    "sandbox",
    *_CLAUDE_SCRIPTS.values(),
    *_CODEX_SCRIPTS.values(),
}


@dataclass(frozen=True)
class LegacyInspection:
    contribution: Contribution
    migrated: tuple[str, ...]
    conflicts: tuple[str, ...]


def _digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _is_legacy_command(command: object, script: str, *, codex: bool) -> bool:
    if not isinstance(command, str) or _MARKETPLACE not in command:
        return False
    try:
        argv = shlex.split(command)
    except ValueError:
        return False
    expected_length = 2 if codex else 1
    return (
        len(argv) == expected_length
        and (not codex or argv[0] == "python3")
        and Path(argv[-1]).name == script
        and "/scripts/" in argv[-1]
    )


def _is_exact_legacy_entry(
    relative: str, event: str, entry: object, script: str
) -> bool:
    if not isinstance(entry, dict):
        return False
    codex = relative == ".codex/hooks.json"
    matchers = {
        "PreToolUse": "^apply_patch$" if codex else "Edit|Write|MultiEdit|Bash",
        "PostToolUse": {"^apply_patch$", "^exec_command$"} if codex else ".*",
    }
    expected_outer = {"hooks"}
    expected_matcher = matchers.get(event)
    if expected_matcher is not None:
        expected_outer.add("matcher")
        actual = entry.get("matcher")
        if isinstance(expected_matcher, set):
            if actual not in expected_matcher:
                return False
        elif actual != expected_matcher:
            return False
    if set(entry) != expected_outer:
        return False
    hooks = entry.get("hooks")
    if not isinstance(hooks, list) or len(hooks) != 1 or not isinstance(hooks[0], dict):
        return False
    hook = hooks[0]
    expected_hook_keys = {"type", "command", "timeout"}
    if not codex and event == "UserPromptSubmit":
        expected_hook_keys = {"type", "command", "statusMessage"}
        if hook.get("statusMessage") != "Logging to chat_log.md":
            return False
    elif hook.get("timeout") != 5000:
        return False
    return (
        set(hook) == expected_hook_keys
        and hook.get("type") == "command"
        and _is_legacy_command(hook.get("command"), script, codex=codex)
    )


def _is_exact_monitor_entry(entry: object) -> bool:
    return entry == {
        "matcher": "",
        "hooks": [{"type": "command", "command": _LEGACY_MONITOR_COMMAND}],
    }


def _mentions_monitor_wiring(value: object) -> bool:
    serialized = json.dumps(value, sort_keys=True)
    return "monitor-nudge" in serialized or _LEGACY_MONITOR_COMMAND in serialized


def _migrate_hook_file(
    root: Path,
    relative: str,
    desired: dict,
    scripts: dict[str, str],
    include_hooks: bool,
) -> tuple[ExactFileIntent | None, str | None, bool]:
    path = root / relative
    if not path.exists() and not path.is_symlink():
        return None, None, False
    if path.is_symlink() or not path.is_file():
        return None, (
            f"{relative}: manual conflict (hook path is not a regular file; "
            "replace it with a regular file or remove it, then rerun pb-tasks init)"
        ), False
    text = path.read_text(encoding="utf-8", errors="replace")
    try:
        document = json.loads(text)
    except json.JSONDecodeError:
        if _MARKETPLACE in text:
            return None, (
                f"{relative}: manual conflict (legacy hook JSON is malformed; "
                "repair or remove the legacy entry, then rerun pb-tasks init)"
            ), False
        return None, None, False
    if not isinstance(document, dict) or not isinstance(document.get("hooks"), dict):
        if _MARKETPLACE in text:
            return None, (
                f"{relative}: manual conflict (legacy hook shape is unknown; "
                "remove only the legacy Playbook entry, then rerun pb-tasks init)"
            ), False
        return None, None, False

    found = False
    marketplace_found = False
    unsafe = False
    retained: dict[str, list] = {}
    for event, entries in document["hooks"].items():
        if not isinstance(entries, list):
            unsafe |= _MARKETPLACE in json.dumps(entries)
            retained[event] = entries
            continue
        kept = []
        for entry in entries:
            serialized = json.dumps(entry)
            expected_script = scripts.get(event)
            legacy = (
                expected_script is not None
                and _is_exact_legacy_entry(
                    relative, event, entry, expected_script
                )
            )
            if legacy:
                found = True
                marketplace_found = True
            elif relative == ".claude/settings.json" and _is_exact_monitor_entry(entry):
                found = True
            else:
                unsafe |= _MARKETPLACE in serialized or _mentions_monitor_wiring(entry)
                kept.append(entry)
        retained[event] = kept
    if unsafe:
        return None, (
            f"{relative}: manual conflict (unrecognized Marketplace hook entry; "
            "remove only that legacy entry, then rerun pb-tasks init)"
        ), False
    if not found:
        return None, None, False
    if not include_hooks:
        return None, f"{relative}: manual conflict (--no-hooks preserves active legacy hooks)", False

    if marketplace_found:
        for event, entries in desired["hooks"].items():
            current = retained.setdefault(event, [])
            for entry in entries:
                if entry not in current:
                    current.append(entry)
    document["hooks"] = {event: entries for event, entries in retained.items() if entries}
    content = json.dumps(document, indent=2, ensure_ascii=False) + "\n"
    return ExactFileIntent(relative, content, _digest(text)), None, True


def _enabled_plugin_conflict(path: Path, label: str) -> str | None:
    if not path.is_file():
        return None
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    try:
        value = json.loads(text)
    except json.JSONDecodeError:
        if _PLUGIN_KEY in text:
            return (
                f"{label}: manual conflict (cannot determine legacy plugin "
                "enablement from malformed settings; repair settings and rerun init)"
            )
        return None
    enabled = value.get("enabledPlugins") if isinstance(value, dict) else None
    if isinstance(enabled, dict) and enabled.get(_PLUGIN_KEY) is True:
        return (
            f"{label}: manual conflict: enabledPlugins activates {_PLUGIN_KEY}; "
            "disable or uninstall the legacy Claude plugin"
        )
    return None


def _is_active_consumer_path(path: Path, relative: str) -> bool:
    parts = Path(relative).parts
    # Claude worktrees are independent project copies.  Their logs, task
    # evidence, and old generated files are not execution surfaces of the root
    # being initialized and must not make that root's migration impossible.
    if relative.startswith(".claude/worktrees/"):
        return False
    return bool(
        relative in _ACTIVE_CONSUMER_FILES
        or parts and parts[0] in _ACTIVE_CONSUMER_DIRS
        or path.stat().st_mode & 0o111
    )


def _has_direct_legacy_runtime_reference(text: str) -> bool:
    for line in text.splitlines():
        if "/.claude/plugins/" not in line or "/playbook/" not in line:
            continue
        if any(f"/scripts/{name}" in line for name in _LEGACY_RUNTIME_NAMES):
            return True
    return False


def _settings_has_active_legacy_runtime_reference(text: str) -> bool:
    """Check executable settings fields, excluding permission-history text."""
    try:
        value = json.loads(text)
    except json.JSONDecodeError:
        return _has_direct_legacy_runtime_reference(text)
    if not isinstance(value, dict):
        return False
    # `permissions` entries merely remember commands a user once approved;
    # they do not execute them. Hook commands do execute and remain conflicts.
    return _has_direct_legacy_runtime_reference(
        json.dumps(value.get("hooks", {}), ensure_ascii=False)
    )


def inspect_legacy_project(
    root: Path, *, include_hooks: bool, home: Path | None = None
) -> LegacyInspection:
    intents: list[ExactFileIntent | ExactDeleteIntent] = []
    migrated: list[str] = []
    conflicts: list[str] = []
    excluded: set[str] = set()

    resolved_home = home or Path.home()
    for settings, label in (
        (resolved_home / ".claude/settings.json", "~/.claude/settings.json"),
        (root / ".claude/settings.json", ".claude/settings.json"),
        (root / ".claude/settings.local.json", ".claude/settings.local.json"),
    ):
        conflict = _enabled_plugin_conflict(settings, label)
        if conflict:
            conflicts.append(conflict)

    for relative, (legacy_command, current_command) in _LAUNCHERS.items():
        path = root / relative
        excluded.add(relative)
        if not path.exists() and not path.is_symlink():
            continue
        if path.is_symlink() or not path.is_file():
            conflicts.append(
                f"{relative}: manual conflict (launcher is not a regular file; "
                f"replace it with `exec {current_command} \"$@\"` or remove it)"
            )
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        legacy = _LEGACY_LAUNCHER.format(command=legacy_command)
        current = _SHIM.format(command=current_command)
        if text == current:
            continue
        if text == legacy:
            intents.append(ExactFileIntent(relative, current, _digest(text), mode=0o755))
            migrated.append(relative)
        elif "playbook-managed — do not edit; regenerated by playbook plugin" in text or _has_direct_legacy_runtime_reference(text):
            conflicts.append(
                f"{relative}: manual conflict (modified or foreign launcher; "
                f"inspect it, then replace with `exec {current_command} \"$@\"` "
                "or remove it)"
            )
        # A launcher with no Marketplace runtime reference is outside legacy
        # migration ownership. Preserve it; project reconciliation does not
        # need to replace a working development/user wrapper.

    monitor_launcher = root / ".claude/bin/monitor"
    excluded.add(".claude/bin/monitor")
    if monitor_launcher.exists() or monitor_launcher.is_symlink():
        if monitor_launcher.is_symlink() or not monitor_launcher.is_file():
            conflicts.append(
                ".claude/bin/monitor: manual conflict (monitor launcher is not a regular file)"
            )
        else:
            text = monitor_launcher.read_text(encoding="utf-8", errors="replace")
            if text == _LEGACY_MONITOR_LAUNCHER:
                intents.append(
                    ExactDeleteIntent(
                        ".claude/bin/monitor", _digest(text), expected_mode=0o755
                    )
                )
                migrated.append(".claude/bin/monitor")
            elif "playbook-managed" in text or "scripts/monitor" in text:
                conflicts.append(
                    ".claude/bin/monitor: manual conflict (modified generated monitor launcher; inspect or remove it)"
                )

    monitor_hook = root / ".claude/hooks/monitor-nudge.sh"
    excluded.add(".claude/hooks/monitor-nudge.sh")
    if monitor_hook.exists() or monitor_hook.is_symlink():
        if monitor_hook.is_symlink() or not monitor_hook.is_file():
            conflicts.append(
                ".claude/hooks/monitor-nudge.sh: manual conflict (monitor hook is not a regular file)"
            )
        else:
            text = monitor_hook.read_text(encoding="utf-8", errors="replace")
            digest = _digest(text)
            if digest in _LEGACY_MONITOR_HOOK_DIGESTS:
                intents.append(
                    ExactDeleteIntent(
                        ".claude/hooks/monitor-nudge.sh",
                        digest,
                        expected_mode=0o755,
                        hook=True,
                    )
                )
                migrated.append(".claude/hooks/monitor-nudge.sh")
            elif "monitor-nudge" in text or ".agent/monitor" in text:
                conflicts.append(
                    ".claude/hooks/monitor-nudge.sh: manual conflict (modified generated monitor hook; inspect or remove it)"
                )

    for relative, desired, scripts in (
        (".codex/hooks.json", codex_hooks(), _CODEX_SCRIPTS),
        (".claude/settings.json", claude_hooks(), _CLAUDE_SCRIPTS),
    ):
        excluded.add(relative)
        intent, conflict, changed = _migrate_hook_file(
            root, relative, desired, scripts, include_hooks
        )
        if intent:
            intents.append(intent)
        if conflict:
            conflicts.append(conflict)
        if changed:
            migrated.append(relative)

    for path in root.rglob("*"):
        if not path.is_file() or path.is_symlink():
            continue
        relative = path.relative_to(root).as_posix()
        if relative in excluded or relative.startswith(".agent/") or relative.startswith(".git/"):
            continue
        if not _is_active_consumer_path(path, relative):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        active_reference = (
            _settings_has_active_legacy_runtime_reference(text)
            if relative == ".claude/settings.local.json"
            else _has_direct_legacy_runtime_reference(text)
        )
        if active_reference:
            conflicts.append(
                f"{relative}: manual conflict (active direct Marketplace consumer; "
                "replace the direct plugin path with the corresponding pb-* command)"
            )

    return LegacyInspection(
        Contribution("legacy-migration", tuple(intents)),
        tuple(sorted(migrated)),
        tuple(sorted(set(conflicts))),
    )
